version: '3.8'

services:
  backend:
    depends_on:
      - db
    build:
      context: .
      target: runtime
      args:
        ENV: production
    restart: always
    env_file:
      - conf/.env
    volumes:
      - ./:/app

  db:
    image: mariadb
    restart: always
    env_file:
      - conf/db.env
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
