version: '3.8'

services:
  backend:
    depends_on:
      - db
    build:
      context: .
      target: runtime
    restart: always
    env_file:
      - conf/.env
    volumes:
      - ./:/app
  
  db:
    image: postgres
    restart: always
    env_file:
      - conf/db.env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
